@echo off
echo ==========================================
echo  BK - Verification et push de gradlew
echo ==========================================
echo.

cd /d "%~dp0"

echo Verification du fichier gradlew...
if not exist "gradlew" (
    echo ERREUR: gradlew n'existe pas localement!
    echo.
    echo Recreation du fichier gradlew...
    goto create_gradlew
)

echo Le fichier gradlew existe.
echo.
echo Verification du statut git...
git status --short

echo.
echo Ajout de gradlew au repo...
git add gradlew

echo Commit...
git commit -m "Ajout du fichier gradlew manquant"

echo Push vers GitHub...
git push origin main

echo.
echo ==========================================
echo  FAIT !
echo ==========================================
echo.
echo Le fichier gradlew a ete push sur GitHub.
echo Allez sur GitHub Actions pour voir le build.
pause
exit /b 0

:create_gradlew
echo Creation d'un gradlew minimal...
echo #!/bin/sh > gradlew
echo. >> gradlew
echo ############################################################################## >> gradlew
echo ## Gradle start up script for POSIX generated by Gradle. >> gradlew
echo ############################################################################## >> gradlew
echo. >> gradlew
echo # Attempt to set APP_HOME >> gradlew
echo app_path=$0 >> gradlew
echo. >> gradlew
echo # Need this for daisy-chained symlinks. >> gradlew
echo while >> gradlew
echo     APP_HOME=${app_path%%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path >> gradlew
echo     [ -h "$app_path" ] >> gradlew
echo do >> gradlew
echo     ls=$( ls -ld "$app_path" ) >> gradlew
echo     link=${ls#*' -^> '} >> gradlew
echo     case $link in             #( >> gradlew
echo       /*)   app_path=$link ;; #( >> gradlew
echo       *)    app_path=$APP_HOME$link ;; >> gradlew
echo     esac >> gradlew
echo done >> gradlew
echo. >> gradlew
echo APP_BASE_NAME=${0##*/} >> gradlew
echo APP_HOME=$( cd "${APP_HOME:-./}" ^&^& pwd -P ) ^|^| exit >> gradlew
echo. >> gradlew
echo # Use the maximum available, or set MAX_FD != -1 to use that value. >> gradlew
echo MAX_FD=maximum >> gradlew
echo. >> gradlew
echo warn () { >> gradlew
echo     echo "$*" >> gradlew
echo } ^>^&2 >> gradlew
echo. >> gradlew
echo die () { >> gradlew
echo     echo >> gradlew
echo     echo "$*" >> gradlew
echo     echo >> gradlew
echo     exit 1 >> gradlew
echo } ^>^&2 >> gradlew
echo. >> gradlew
echo cygwin=false >> gradlew
echo msys=false >> gradlew
echo darwin=false >> gradlew
echo nonstop=false >> gradlew
echo case "$( uname )" in                #( >> gradlew
echo   CYGWIN* )         cygwin=true  ;; #( >> gradlew
echo   Darwin* )         darwin=true  ;; #( >> gradlew
echo   MSYS* ^| MINGW* )  msys=true    ;; #( >> gradlew
echo   NONSTOP* )        nonstop=true ;; >> gradlew
echo esac >> gradlew
echo. >> gradlew
echo CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar >> gradlew
echo. >> gradlew
echo if [ -n "$JAVA_HOME" ] ; then >> gradlew
echo     if [ -x "$JAVA_HOME/jre/sh/java" ] ; then >> gradlew
echo         JAVACMD=$JAVA_HOME/jre/sh/java >> gradlew
echo     else >> gradlew
echo         JAVACMD=$JAVA_HOME/bin/java >> gradlew
echo     fi >> gradlew
echo     if [ ! -x "$JAVACMD" ] ; then >> gradlew
echo         die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >> gradlew
echo     fi >> gradlew
echo else >> gradlew
echo     JAVACMD=java >> gradlew
echo     which java ^>/dev/null 2^>^&1 ^|^| die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >> gradlew
echo fi >> gradlew
echo. >> gradlew
echo set -- \ >> gradlew
echo         "-Dorg.gradle.appname=$APP_BASE_NAME" \ >> gradlew
echo         -classpath "$CLASSPATH" \ >> gradlew
echo         org.gradle.wrapper.GradleWrapperMain \ >> gradlew
echo         "$@" >> gradlew
echo. >> gradlew
echo exec "$JAVACMD" "$@" >> gradlew

echo.
echo Fichier gradlew recree!
goto end

:end
echo.
echo Ajout de gradlew au repo...
git add gradlew

echo Commit...
git commit -m "Ajout du fichier gradlew"

echo Push vers GitHub...
git push origin main

echo.
echo ==========================================
echo  FAIT !
echo ==========================================
echo.
pause
